name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.12

  test-unit:
    uses: Workiva/gha-dart-oss/.github/workflows/test-unit.yaml@v0.1.12